version: 2.1
jobs:
  build:
    working_directory: ~/project
    environment:
      SENTRY_ORG: sentry-test-wh
      SENTRY_PROJECT: angular
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
#      # [AUTH NOTE]
#      # Please, check out [AUTH NOTE] at "Deploy Master to GitHub Pages" Step
#      - add_ssh_keys:
#          fingerprints:
#            - "27:0f:d9:4b:88:1a:c3:84:da:d5:22:70:67:39:f8:6f"
      - run:
          name: Set environment variables for gh-pages
          command: |
            echo 'export GIT_COMMIT_AUTHOR_NAME=$(eval git log --format=%an -n 1 ${CIRCLE_SHA1})' >> $BASH_ENV
            echo 'export GIT_COMMIT_AUTHOR_EMAIL=$(eval git log --format=%ae -n 1 ${CIRCLE_SHA1})' >> $BASH_ENV
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Show current directory
          command: pwd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
#      # Split those two steps to separate jobs
#      - run:
#          name: Linting
#          command: npm run lint
#      - run:
#          name: Testing
#          command: npm run test
      - run:
          name: Building
          command: npm run build:production
      - run:
          name: Deploy to Sentry
          command: npm run sentry-release:production
      - run:
          name: Remove source maps
          command: npm run remove-source-maps
      # [AUTH NOTE]
      # To be able to run gh-pages you have to add permissions (keys)
      # between CircleCI and GitHub
      # https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
      # ssh-keygen -C "your.mail@gmail.com" -f key-file-name
      # key-file-name | pbcopy
      - run:
          name: Deploy Master to GitHub Pages
          command: ./node_modules/gh-pages/bin/gh-pages.js -b gh-pages -d dist/liki-devtalk-sentry -u "${GIT_COMMIT_AUTHOR_NAME} <${GIT_COMMIT_AUTHOR_EMAIL}>" -m "[skip ci] Update"
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
            - package.json

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # run only when new tag is created (v.3 v.3.1)
            tags:
              only: /^v.*/
